# Generated by Django 5.2.16 on 2026-07-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=100)),
                ('lien', models.CharField()),
                ('date_publication', models.DateField()),
                ('source', models.CharField()),
                ('filier_tag', models.CharField(max_length=50)),
                ('has_unique', models.CharField(max_length=64, unique=True)),
                ('date_extraction', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('filier', models.CharField(max_length=300)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('desactif', 'Desactif')], default='actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Envois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('succes', 'Succes'), ('echec', 'Echec')], max_length=50)),
                ('nb_offres_envoyees', models.IntegerField()),
                ('Utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
        ),
    ]
