# Generated by Django 5.2.16 on 2026-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
