# Generated by Django 5.2.16 on 2026-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_offres_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='lien',
            field=models.CharField(max_length=500),
        ),
    ]
